// Initialize an empty shopping cart array
let cart = [];

// Define an array of products with their categories, names, and prices
const products = [
    {
        "nr": "10001",
        "artikelid": "25053",
        "varnummer": "100",
        "name": "Braastad XO",
        "name2": "",
        "price": "442.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2000-08-07",
        "slutlev": " ",
        "category": "Cognac",
        "forpackning": "Flaska",
        "forslutning": "Naturkork",
        "ursprung": "Cognac, Fine Champagne",
        "ursprunglandname": "Frankrike",
        "producent": "Tiffon",
        "leverantor": "Arcus Sweden AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "40%",
        "modul": "",
        "sortiment": "FS",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1001",
        "artikelid": "190719",
        "varnummer": "10",
        "name": "Vanlig Vodka",
        "name2": "",
        "price": "195.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2006-04-01",
        "slutlev": " ",
        "category": "Okryddad sprit",
        "forpackning": "Flaska",
        "forslutning": "Skruvkapsyl",
        "ursprung": "",
        "ursprunglandname": "Sverige",
        "producent": "Svensk Export Vodka AB",
        "leverantor": "Fondberg",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "37.5%",
        "modul": "",
        "sortiment": "FS",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1001201",
        "artikelid": "51029",
        "varnummer": "10012",
        "name": "Dworek Vodka",
        "name2": "",
        "price": "190.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2004-12-06",
        "slutlev": " ",
        "category": "Okryddad sprit",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandname": "Polen",
        "producent": "Tarpan Fabryka Likierow",
        "leverantor": "TIWA Trading AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "37.5%",
        "modul": "",
        "sortiment": "FS",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1001202",
        "artikelid": "407506",
        "varnummer": "10012",
        "name": "Dworek Vodka",
        "name2": "",
        "price": "100.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2009-10-01",
        "slutlev": " ",
        "category": "Okryddad sprit",
        "forpackning": "Flaska",
        "forslutning": "Skruvkapsyl",
        "ursprung": "",
        "ursprunglandname": "Polen",
        "producent": "Tarpan Fabryka Likierow",
        "leverantor": "TIWA Trading AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "37.5%",
        "modul": "",
        "sortiment": "FS",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1003802",
        "artikelid": "513291",
        "varnummer": "10038",
        "name": "Esping Jul BÃ\u00a4sk",
        "name2": "",
        "price": "195.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2010-11-15",
        "slutlev": " ",
        "category": "Kryddad sprit",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandname": "Sverige",
        "producent": "Symposion International",
        "leverantor": "Symposion International AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "32%",
        "modul": "",
        "sortiment": "TSS",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1004703",
        "artikelid": "723841",
        "varnummer": "10047",
        "name": "Nils Oscar",
        "name2": "Celebration Ale",
        "price": "43.70",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-02-01",
        "slutlev": " ",
        "category": "Ã–l, Ale",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandname": "Sverige",
        "producent": "Nils Oscar Company",
        "leverantor": "The Nils Oscar Company AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "9.4%",
        "modul": "T5",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1004801",
        "artikelid": "733051",
        "varnummer": "10048",
        "name": "Rhum J. M",
        "name2": "",
        "price": "729.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-03-01",
        "slutlev": " ",
        "category": "Rom, MÃ\u00b6rk",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Martinique",
        "ursprunglandname": "Frankrike",
        "producent": "Les Heritiers Crassous de Mede",
        "leverantor": "Cask Sweden AB",
        "argang": "2001",
        "provadargang": "",
        "alkoholhalt": "46.6%",
        "modul": "T7",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1004901",
        "artikelid": "733068",
        "varnummer": "10049",
        "name": "Rhum J.M",
        "name2": "",
        "price": "1399.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-04-02",
        "slutlev": " ",
        "category": "Rom, MÃ\u00b6rk",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Martinique",
        "ursprunglandname": "Frankrike",
        "producent": "Les Heritiers Crassous de Mede",
        "leverantor": "Cask Sweden AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "44.8%",
        "modul": "T7",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1005001",
        "artikelid": "733084",
        "varnummer": "10050",
        "name": "Balcones Texas",
        "name2": "",
        "price": "899.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-03-01",
        "slutlev": " ",
        "category": "Whisky, Malt",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandname": "USA",
        "producent": "Balcones Distilling",
        "leverantor": "Cask Sweden AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "52.2%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1005101",
        "artikelid": "733200",
        "varnummer": "10051",
        "name": "Balcones Brimstone",
        "name2": "",
        "price": "899.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-03-01",
        "slutlev": " ",
        "category": "Whisky, Ã–vrig",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandname": "USA",
        "producent": "Balcones Distilling",
        "leverantor": "Cask Sweden AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "53.2%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1005201",
        "artikelid": "733236",
        "varnummer": "10052",
        "name": "Balcones True Blue",
        "name2": "",
        "price": "899.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-03-01",
        "slutlev": " ",
        "category": "Whisky, Ã–vrig",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandname": "USA",
        "producent": "Balcones Distilling",
        "leverantor": "Cask Sweden AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "50.2%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1005401",
        "artikelid": "733429",
        "varnummer": "10054",
        "name": "Linkwood",
        "name2": "the Octave",
        "price": "1159.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-03-01",
        "slutlev": " ",
        "category": "Whisky, Malt",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Skottland, Highlands, Speyside",
        "ursprunglandname": "Storbritannien",
        "producent": "Duncan Taylor Scotch Whisky",
        "leverantor": "Clydesdale AB",
        "argang": "1989",
        "provadargang": "",
        "alkoholhalt": "51.7%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1005502",
        "artikelid": "733446",
        "varnummer": "10055",
        "name": "Marolo",
        "name2": "Grappa di Arneis Vigneto Renesio",
        "price": "481.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-03-01",
        "slutlev": " ",
        "category": "Grappa och Marc, Grappa",
        "forpackning": "Flaska",
        "forslutning": "Naturkork",
        "ursprung": "",
        "ursprunglandname": "Italien",
        "producent": "Distilleria St Teresa dei Frat",
        "leverantor": "Haugen-Gruppen AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "50%",
        "modul": "T7",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1005602",
        "artikelid": "733468",
        "varnummer": "10056",
        "name": "ClÃ\u00a9ment",
        "name2": "Single Cask",
        "price": "529.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-04-02",
        "slutlev": " ",
        "category": "Rom, MÃ\u00b6rk",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Martinique",
        "ursprunglandname": "Frankrike",
        "producent": "Les Heritiers Crassous de Mede",
        "leverantor": "Cask Sweden AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "47.6%",
        "modul": "T7",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "101",
        "artikelid": "1",
        "varnummer": "1",
        "name": "Renat",
        "name2": "",
        "price": "203.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "1993-10-01",
        "slutlev": " ",
        "category": "Okryddad sprit",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandname": "Internationellt mÃ\u00a4rke",
        "producent": "Pernod Ricard",
        "leverantor": "Pernod Ricard Sweden AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "37.5%",
        "modul": "",
        "sortiment": "FS",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1010001",
        "artikelid": "817007",
        "varnummer": "10100",
        "name": "Romano Levi",
        "name2": "Mostaco d\u00c2\u00b4Asti Donna Selvatica",
        "price": "790.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-04-01",
        "slutlev": " ",
        "category": "Grappa och Marc, Grappa",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandname": "Italien",
        "producent": "Distilleria Levi Serafino ( di",
        "leverantor": "Haugen-Gruppen AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "40%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1010404",
        "artikelid": "611864",
        "varnummer": "10104",
        "name": "Giare 5 Grappe",
        "name2": "Moscato, Amarone, Teroldego, Chardonnay, Prosecco",
        "price": "399.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-03-01",
        "slutlev": " ",
        "category": "Grappa och Marc, Grappa",
        "forpackning": "5 flaskor Ã\u00a0 100 ml",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandname": "Italien",
        "producent": "Marzadro",
        "leverantor": "Stragas-Gruppen AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "40%",
        "modul": "",
        "sortiment": "TST",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1010501",
        "artikelid": "659534",
        "varnummer": "10105",
        "name": "Genuin 25",
        "name2": "",
        "price": "149.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-09-01",
        "slutlev": " ",
        "category": "Okryddad sprit",
        "forpackning": "Flaska",
        "forslutning": "Skruvkapsyl",
        "ursprung": "",
        "ursprunglandname": "Sverige",
        "producent": "Svensk Vodka i Motala AB",
        "leverantor": "Svensk Vodka i Motala AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "25%",
        "modul": "",
        "sortiment": "TST",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1011302",
        "artikelid": "723428",
        "varnummer": "10113",
        "name": "Kullados",
        "name2": "",
        "price": "499.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-04-02",
        "slutlev": " ",
        "category": "Ã–vrig sprit",
        "forpackning": "Flaska",
        "forslutning": "Plastkork\/syntetkork",
        "ursprung": "",
        "ursprunglandname": "Sverige",
        "producent": "Kullabygdens Musteri AB",
        "leverantor": "Kullabygdens Destilleri AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "40%",
        "modul": "T5",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1011401",
        "artikelid": "811782",
        "varnummer": "10114",
        "name": "Grappa Riserva Levi Romano",
        "name2": "Distilleria Levi Serafino Donna Selvatica",
        "price": "989.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-03-01",
        "slutlev": " ",
        "category": "Grappa och Marc, Grappa",
        "forpackning": "Flaska",
        "forslutning": "Naturkork",
        "ursprung": "",
        "ursprunglandname": "Italien",
        "producent": "Distilleria Levi Serafino ( di",
        "leverantor": "Haugen-Gruppen AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "50%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1011601",
        "artikelid": "614078",
        "varnummer": "10116",
        "name": "Glenmorangie",
        "name2": "Pride",
        "price": "24500.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-02-23",
        "slutlev": " ",
        "category": "Whisky, Malt",
        "forpackning": "Flaska",
        "forslutning": "Naturkork",
        "ursprung": "Skottland, Highlands, Northern Highlands",
        "ursprunglandname": "Storbritannien",
        "producent": "Glenmorangie",
        "leverantor": "MoÃ\u00abt Hennessy Sverige AB",
        "argang": "1981",
        "provadargang": "",
        "alkoholhalt": "56.7%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1011701",
        "artikelid": "734763",
        "varnummer": "10117",
        "name": "The Arran Malt",
        "name2": "Orkney Bere",
        "price": "579.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-04-02",
        "slutlev": " ",
        "category": "Whisky, Malt",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Skottland, Highlands, Islands, Arran",
        "ursprunglandname": "Storbritannien",
        "producent": "Isle of Arran Distillers",
        "leverantor": "Cask Sweden AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "46%",
        "modul": "T7",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1011901",
        "artikelid": "614800",
        "varnummer": "10119",
        "name": "Glen Garioch",
        "name2": "Mackillop's Choice",
        "price": "895.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-02-01",
        "slutlev": " ",
        "category": "Whisky, Malt",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Skottland, Highlands",
        "ursprunglandname": "Storbritannien",
        "producent": "Angus Dundee",
        "leverantor": "Philipson SÃ\u00b6derberg AB",
        "argang": "1990",
        "provadargang": "",
        "alkoholhalt": "43%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1012601",
        "artikelid": "874805",
        "varnummer": "10126",
        "name": "Nikka Taketsuru",
        "name2": "Pure Malt",
        "price": "549.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-10-03",
        "slutlev": " ",
        "category": "Whisky, Malt",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandname": "Japan",
        "producent": "The Nikka Whisky Distilling Co",
        "leverantor": "Symposion International AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "43%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1013104",
        "artikelid": "734572",
        "varnummer": "10131",
        "name": "Poli Grappa Barrel Pack",
        "name2": "",
        "price": "549.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-04-02",
        "slutlev": " ",
        "category": "Grappa och Marc, Grappa",
        "forpackning": "5 flaskor Ã\u00a0 100 ml",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandname": "Italien",
        "producent": "Distillerie Poli",
        "leverantor": "Bibendum",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "40%",
        "modul": "T7",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1013201",
        "artikelid": "633539",
        "varnummer": "10132",
        "name": "Linkwood",
        "name2": "Duthies 23 Years",
        "price": "950.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-03-01",
        "slutlev": " ",
        "category": "Whisky , Malt",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Skottland, Highlands, Speyside",
        "ursprunglandname": "Storbritannien",
        "producent": "William Cadenhead",
        "leverantor": "Symposion International AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "46%",
        "modul": "T7",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1013901",
        "artikelid": "871188",
        "varnummer": "10139",
        "name": "Longmorn",
        "name2": "16 Years",
        "price": "1095.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-10-03",
        "slutlev": " ",
        "category": "Whisky, Malt",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Skottland",
        "ursprunglandname": "Storbritannien",
        "producent": "Sansibar Whisky",
        "leverantor": "Symposion International AB",
        "argang": "1997",
        "provadargang": "",
        "alkoholhalt": "48.5%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1014002",
        "artikelid": "634582",
        "varnummer": "10140",
        "name": "Braunstein",
        "name2": "Library Collection 11:1",
        "price": "999.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-03-01",
        "slutlev": " ",
        "category": "Whisky, Malt",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandname": "Danmark",
        "producent": "Bryghuset Braunstein",
        "leverantor": "Galatea Spirits AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "46%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1014301",
        "artikelid": "734788",
        "varnummer": "10143",
        "name": "Waqar Pisco",
        "name2": "",
        "price": "449.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-04-02",
        "slutlev": " ",
        "category": "Brandy och Vinsprit, Vinsprit",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandname": "Chile",
        "producent": "TulahuÃ\u00a9n",
        "leverantor": "N57 Nordic AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "40%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1014804",
        "artikelid": "638540",
        "varnummer": "10148",
        "name": "Esprit Calvados 5 domaines",
        "name2": "",
        "price": "695.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-04-02",
        "slutlev": " ",
        "category": "Calvados",
        "forpackning": "5 flaskor Ã\u00a0 100 ml",
        "forslutning": "",
        "ursprung": "Normandie, Calvados, Calvados du Pays d'",
        "ursprunglandname": "Frankrike",
        "producent": "Esprit Calvados 5 domaines",
        "leverantor": "Symposion International AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "42%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1015001",
        "artikelid": "638546",
        "varnummer": "10150",
        "name": "The Spice Tree",
        "name2": "",
        "price": "499.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-04-02",
        "slutlev": " ",
        "category": "Whisky , Malt",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Skottland",
        "ursprunglandname": "Storbritannien",
        "producent": "Compass Box",
        "leverantor": "Symposion International AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "46%",
        "modul": "T7",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1015101",
        "artikelid": "707630",
        "varnummer": "10151",
        "name": "Grappa di Levi",
        "name2": "Levi Romano",
        "price": "3446.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-12-01",
        "slutlev": " ",
        "category": "Grappa och Marc, Grappa",
        "forpackning": "Flaska",
        "forslutning": "Naturkork",
        "ursprung": "",
        "ursprunglandname": "Italien",
        "producent": "Levi Romano",
        "leverantor": "Haugen-Gruppen AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "50%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1015301",
        "artikelid": "723096",
        "varnummer": "10153",
        "name": "Highland Park",
        "name2": "Norse Gods Loki",
        "price": "1399.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-04-02",
        "slutlev": " ",
        "category": "Whisky, Malt",
        "forpackning": "Flaska",
        "forslutning": "Naturkork",
        "ursprung": "Skottland, Highlands, Islands, Orkney",
        "ursprunglandname": "Storbritannien",
        "producent": "Highland Park",
        "leverantor": "Edrington Sweden AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "48.7%",
        "modul": "T5",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1015601",
        "artikelid": "828902",
        "varnummer": "10156",
        "name": "Bocchino Riserva Cantina Privata",
        "name2": "18 Years",
        "price": "749.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-05-02",
        "slutlev": " ",
        "category": "Grappa och Marc, Grappa",
        "forpackning": "Flaska",
        "forslutning": "Plastkork\/syntetkork",
        "ursprung": "",
        "ursprunglandname": "Italien",
        "producent": "Distilleria Bocchino",
        "leverantor": "Brandpartners AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "45%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1015701",
        "artikelid": "611207",
        "varnummer": "10157",
        "name": "Lustau Brandy Solera",
        "name2": "Gran Reserva Finest Selection",
        "price": "499.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-02-01",
        "slutlev": " ",
        "category": "Brandy och Vinsprit, Brandy",
        "forpackning": "Flaska",
        "forslutning": "Naturkork",
        "ursprung": "",
        "ursprunglandname": "Spanien",
        "producent": "Lustau",
        "leverantor": "Hjo Grosshandel AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "40%",
        "modul": "T7",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1015902",
        "artikelid": "854266",
        "varnummer": "10159",
        "name": "Facile",
        "name2": "Arrak",
        "price": "179.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-06-02",
        "slutlev": " ",
        "category": "Ã–vrig sprit",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandname": "Sverige",
        "producent": "Facile & Co",
        "leverantor": "Facile & Co AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "40%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1016101",
        "artikelid": "633586",
        "varnummer": "10161",
        "name": "Benriach",
        "name2": "Liquid Sun 15 Years",
        "price": "799.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-03-01",
        "slutlev": " ",
        "category": "Whisky, Malt",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Skottland, Highlands, Speyside",
        "ursprunglandname": "Storbritannien",
        "producent": "Liquid Sun Whisky",
        "leverantor": "Symposion International AB",
        "argang": "1996",
        "provadargang": "",
        "alkoholhalt": "46%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1016301",
        "artikelid": "639227",
        "varnummer": "10163",
        "name": "Littlemill",
        "name2": "Liquid Sun 22 Years",
        "price": "1399.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-04-19",
        "slutlev": " ",
        "category": "Whisky, Malt",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Skottland, Lowlands",
        "ursprunglandname": "Storbritannien",
        "producent": "Ehrlich & Schneider Gbr.",
        "leverantor": "Symposion International AB",
        "argang": "1989",
        "provadargang": "",
        "alkoholhalt": "52.2%",
        "modul": "T7",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1016501",
        "artikelid": "639258",
        "varnummer": "10165",
        "name": "Compass Box",
        "name2": "Hedonism",
        "price": "725.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-04-02",
        "slutlev": " ",
        "category": "Whisky, Grain",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Skottland",
        "ursprunglandname": "Storbritannien",
        "producent": "Compass Box",
        "leverantor": "Symposion International AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "43%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }, {
        "nr": "1016601",
        "artikelid": "639416",
        "varnummer": "10166",
        "name": "Eau-de-Vie de Prune",
        "name2": "",
        "price": "549.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-04-02",
        "slutlev": " ",
        "category": "Sprit av frukt",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandname": "Frankrike",
        "producent": "Etienne Brana",
        "leverantor": "Divine AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "42%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }
];

// Function to filter and display products by category
function filterCategory(category) {
    const productsDiv = document.getElementById('products');
    productsDiv.innerHTML = ''; // Clear the products display

    // Filter products based on the selected category
    const filteredProducts = products.filter(product => product.category === category);

    // Iterate through filtered products and create elements for each
    filteredProducts.forEach(product => {
        const div = document.createElement('div');
        div.textContent = `${product.name} - ${product.price}kr`;

        // Add an event handler to add the product to the cart when clicked
        div.onclick = function () { addToCart(product.name, product.price); };

        // Append the product element to the products display
        productsDiv.appendChild(div);
    });
}

// Function to display all products when the page is loaded
function displayAllProducts() {
    const productsDiv = document.getElementById('products');
    productsDiv.innerHTML = ''; // Clear the products display

    // Iterate through all products and create elements for each
    products.forEach(product => {
        const div = document.createElement('div');
        div.textContent = `${product.name} - ${product.price}kr`;

        // Add an event handler to add the product to the cart when clicked
        div.onclick = function () { addToCart(product.name, product.price); };

        // Append the product element to the products display
        productsDiv.appendChild(div);
    });
}

// Show all products when the page is loaded
document.addEventListener('DOMContentLoaded', displayAllProducts);

// Function to add a product to the shopping cart
function addToCart(name, price) {
    const itemIndex = cart.findIndex(item => item.name === name);

    if (itemIndex > -1) {
        cart[itemIndex].quantity += 1; // If the item exists in the cart, increase its quantity
    } else {
        cart.push({ name, price, quantity: 1 }); // If the item is not in the cart, add it as a new item
    }

    // Update the cart UI to reflect the changes
    updateCartUI();
}

// Function to update the shopping cart UI
function updateCartUI() {
    const cartItems = document.getElementById('cartItems');
    cartItems.innerHTML = '';

    // Iterate through items in the cart and create list items for each
    cart.forEach(item => {
        const li = document.createElement('li');
        li.textContent = `${item.name} - ${item.price}kr x ${item.quantity}`;
        cartItems.appendChild(li);
    });

    // Update the total price in the UI
    updateTotalPrice();
}

// Function to update the total price in the UI
function updateTotalPrice() {
    const totalPrice = cart.reduce((acc, item) => acc + (item.price * item.quantity), 0);
    document.getElementById('totalPrice').textContent = totalPrice;
}

// Function to clear the shopping cart
function clearCart() {
    cart = [];
    updateCartUI();
}

// Function to get and increment the order number from localStorage
function getOrderNumber() {
    let orderNumber = localStorage.getItem('orderNumber');

    if (!orderNumber) {
        orderNumber = '001';
    } else {
        let nextOrderNumber = parseInt(orderNumber) + 1;
        orderNumber = nextOrderNumber.toString().padStart(3, '0');
    }

    // Update and store the order number in localStorage
    localStorage.setItem('orderNumber', orderNumber);
    return orderNumber;
}

// Function to place an order
function placeOrder() {
    if (cart.length > 0) {
        const orderNumber = getOrderNumber();
        alert(`Order placed successfully. Your order number is ${orderNumber}`);
        clearCart();

        // Auto refresh the page after 3 seconds
        setTimeout(() => {
            window.location.reload();
        }, 3000);
    } else {
        alert('Cart is empty. Please add items to your cart before placing an order.');
    }
}
